name: 'Terraform CI/CD'

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    outputs:
      bastion_ip: ${{ steps.extract.outputs.bastion_ip }}
      monitoring_ip: ${{ steps.extract.outputs.monitoring_ip }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Cache Terraform
      uses: actions/cache@v4
      with:
        path: |
          .terraform
          .terraform.lock.hcl
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf', '**/*.tfvars') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::423623847730:role/TerraformGitHubActionsRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init 

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: terraform apply -auto-approve -input=false

    - name: Wait for infrastructure to stabilize
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: sleep 60

    - name: Terraform Refresh
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: terraform refresh

    - name: Extract IP addresses from Terraform output
      id: extract
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: |
        # Extract bastion IP
        BASTION_IP=$(terraform output -json bastion_public_ip | jq -r '.')
        if [ -z "$BASTION_IP" ]; then
          echo "BASTION_IP is empty, exiting..."
          exit 1
        fi
        echo "BASTION_IP=$BASTION_IP" >> $GITHUB_ENV
        echo "bastion_ip=$BASTION_IP" >> $GITHUB_OUTPUT
        echo "Extracted BASTION_IP: $BASTION_IP"

        # Extract monitoring IP
        MONITORING_IP=$(terraform output -json monitoring_public_ip | jq -r '.')
        if [ -z "$MONITORING_IP" ]; then
          echo "MONITORING_IP is empty, exiting..."
          exit 1
        fi
        echo "MONITORING_IP=$MONITORING_IP" >> $GITHUB_ENV
        echo "monitoring_ip=$MONITORING_IP" >> $GITHUB_OUTPUT
        echo "Extracted MONITORING_IP: $MONITORING_IP"

        # Extract LLM server IPs
        LLM_SERVER_IPS=$(terraform output -json llm_server_ips | jq -r '.[]')
        if [ -z "$LLM_SERVER_IPS" ]; then
          echo "No LLM server IPs found, exiting..."
          exit 1
        fi
        echo "LLM_SERVER_IPS=$LLM_SERVER_IPS"

        # Generate Ansible inventory
        mkdir -p ansible/inventory
        echo "[llm_servers]" > ansible/inventory/dynamic.ini
        i=1
        for ip in $LLM_SERVER_IPS; do
          echo "llm$i ansible_host=$ip ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/c/Users/dmisi/.ssh/bastion-key.pem ansible_ssh_common_args=\"-o ProxyCommand='ssh -W %h:%p -i /mnt/c/Users/dmisi/.ssh/bastion-key.pem ubuntu@$BASTION_IP'\"" >> ansible/inventory/dynamic.ini
          i=$((i + 1))
        done

        echo -e "\n[monitoring]" >> ansible/inventory/dynamic.ini
        echo "monitor ansible_host=$MONITORING_IP ansible_user=ubuntu ansible_ssh_private_key_file=/mnt/c/Users/dmisi/.ssh/bastion-key.pem" >> ansible/inventory/dynamic.ini

        echo "Generated inventory file content:"
        cat ansible/inventory/dynamic.ini

    - name: Upload Ansible Inventory
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      uses: actions/upload-artifact@v4
      with:
        name: ansible-inventory
        path: ansible/inventory/dynamic.ini

  ansible:
    name: 'Ansible Deployment'
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Ansible Inventory
      uses: actions/download-artifact@v4
      with:
        name: ansible-inventory
        path: ansible/inventory

    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        find . -type f

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/bastion-key.pem
        chmod 600 ~/.ssh/bastion-key.pem
        if [ -z "${{ needs.terraform.outputs.bastion_ip }}" ]; then
          echo "BASTION_IP is empty, exiting..."
          exit 1
        fi
        ssh-keyscan -H ${{ needs.terraform.outputs.bastion_ip }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ needs.terraform.outputs.monitoring_ip }} >> ~/.ssh/known_hosts

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Check Ansible Inventory
      run: |
        echo "Ansible inventory content:"
        cat ansible/inventory/dynamic.ini

    - name: Run Ansible Playbook (site.yml)
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        if [ ! -f ansible/playbooks/site.yml ]; then
          echo "File ansible/playbooks/site.yml not found!"
          exit 1
        fi
        ansible-playbook -i ansible/inventory/dynamic.ini ansible/playbooks/site.yml -v
      env:
        ANSIBLE_HOST_KEY_CHECKING: False