name: 'Terraform CI/CD'

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    outputs:
      bastion_ip: ${{ steps.extract.outputs.bastion_ip }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Cache Terraform
      uses: actions/cache@v4
      with:
        path: |
          .terraform
          .terraform.lock.hcl
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf', '**/*.tfvars') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::423623847730:role/TerraformGitHubActionsRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init 

    - name: Terraform Format
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: terraform apply -auto-approve -input=false

    - name: Wait for infrastructure to stabilize
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: sleep 30

    - name: Terraform Refresh
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: terraform refresh

    - name: Extract IP addresses from Terraform output
      id: extract
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      run: |
        # Витягуємо IP бастіона спочатку
        BASTION_IP=$(terraform output -json bastion_public_ip | jq -r '.')
        echo "BASTION_IP=$BASTION_IP" >> $GITHUB_ENV
        echo "bastion_ip=$BASTION_IP" >> $GITHUB_OUTPUT
        echo "Extracted BASTION_IP: $BASTION_IP"

        # Витягуємо IP інстансів
        WEBSERVER_IPS=$(terraform output -json webserver_ips | jq -r '.[]')
        echo "WEBSERVER_IPS=$WEBSERVER_IPS"

        # Генеруємо інвентар
        mkdir -p inventory
        echo "[webservers]" > inventory/dynamic.ini
        if [ -z "$WEBSERVER_IPS" ]; then
          echo "No webserver IPs found, exiting..."
          exit 1
        fi
        for ip in $WEBSERVER_IPS; do
          echo "$ip ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/bastion-key.pem ansible_ssh_common_args=\"-o ProxyCommand='ssh -W %h:%p -i ~/.ssh/bastion-key.pem ubuntu@$BASTION_IP'\"" >> inventory/dynamic.ini
        done
        echo "Generated inventory file content:"
        cat inventory/dynamic.ini

  ansible:
    name: 'Ansible Deployment'
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        find . -type f

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/bastion-key.pem
        chmod 600 ~/.ssh/bastion-key.pem
        if [ -z "${{ needs.terraform.outputs.bastion_ip }}" ]; then
          echo "BASTION_IP is empty, exiting..."
          exit 1
        fi
        ssh-keyscan -H ${{ needs.terraform.outputs.bastion_ip }} >> ~/.ssh/known_hosts

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible Playbook
      run: |
        echo "Current directory: $(pwd)"
        ls -la
        if [ ! -f ansible/playbooks/deploy.yml ]; then
          echo "File ansible/playbooks/deploy.yml not found!"
          exit 1
        fi
        ansible-playbook -i inventory/dynamic.ini ansible/playbooks/deploy.yml -v
      env:
        ANSIBLE_HOST_KEY_CHECKING: False