---
prometheus_user: "prometheus"
prometheus_group: "prometheus"
prometheus_version: "2.53.1"
grafana_port: 3000
prometheus_config_path: "/etc/prometheus/prometheus.yml"
prometheus_binary_path: "/usr/local/bin/prometheus/prometheus"
nginx_log: "/var/log/nginx.log"
openwebui_path: "/opt/openwebui"
openwebui_log: "/var/log/openwebui.log"